/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Rust ChatLab JSON parser. Strict about the format spec: off-spec files
 * error out and the JS side falls back to the pure-TS parser.
 * Usage from JS: `parse()` → `getMeta()` → `takeMembers()` → `takeBatch()` until null.
 */
export declare class ChatlabParser {
  constructor(filePath: string)
  /** Run the full parse on the libuv thread pool. */
  parse(): Promise<unknown>
  /** Poll progress while `parse()` is pending. */
  progress(): NativeParseProgress
  getMeta(): NativeChatlabMeta
  /** Move members out to JS. Callable once. */
  takeMembers(): Array<NativeChatlabMember>
  /** Move the next batch of messages out to JS; null when exhausted. */
  takeBatch(size: number): Array<NativeChatlabMessage> | null
}

/**
 * Rust WeFlow parser. Usage from JS:
 * `parse()` → `getMeta()` → `takeMembers()` → `takeBatch()` until null.
 */
export declare class WeflowParser {
  constructor(filePath: string)
  /** Run the full parse on the libuv thread pool. */
  parse(): Promise<unknown>
  /** Poll progress while `parse()` is pending. */
  progress(): NativeParseProgress
  getMeta(): NativeWeflowMeta
  /** Move members (with avatars) out to JS. Callable once. */
  takeMembers(): Array<NativeParsedMember>
  /** Move the next batch of messages out to JS; null when exhausted. */
  takeBatch(size: number): Array<NativeParsedMessage> | null
}

export interface NativeChatlabMember {
  platformId: string
  accountName: string
  groupNickname?: string
  avatar?: string
  roles?: Array<NativeMemberRole>
}

export interface NativeChatlabMessage {
  platformMessageId?: string
  senderPlatformId: string
  senderAccountName: string
  senderGroupNickname?: string
  timestamp: number
  /** Numeric MessageType enum value from shared-types. */
  messageType: number
  /** undefined here means the source `content` was JSON null. */
  content?: string
  replyToMessageId?: string
}

export interface NativeChatlabMeta {
  name: string
  /** Passthrough of `meta.type` ("group" when missing), matching the TS parser. */
  chatType: string
  /** Passthrough of `meta.platform` ("unknown" when missing). */
  platform: string
  groupId?: string
  groupAvatar?: string
  /**
   * true when members came from the top-level `members` array;
   * false when collected from messages (TS emits different object shapes).
   */
  membersFromHead: boolean
  messageCount: number
  memberCount: number
}

export interface NativeMemberRole {
  id: string
  /** Present only when the source role object had a `name` key. */
  name?: string
}

export interface NativeParsedMember {
  platformId: string
  accountName: string
  avatar?: string
}

export interface NativeParsedMessage {
  platformMessageId: string
  senderPlatformId: string
  senderAccountName: string
  /** null when the source `createTime` was JSON null (importer skips those). */
  timestamp?: number
  /** Numeric MessageType enum value from shared-types. */
  messageType: number
  content?: string
}

export interface NativeParseProgress {
  bytesRead: number
  totalBytes: number
  messagesProcessed: number
}

export interface NativeWeflowMeta {
  name: string
  /** "group" | "private" (ChatType enum string values) */
  chatType: string
  groupId?: string
  groupAvatar?: string
  ownerId?: string
  messageCount: number
  memberCount: number
}
